# Generated by Django 2.2.4 on 2019-08-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stpolice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mops',
            name='dps1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dps1', to='stpolice.Distps'),
        ),
    ]
